[[runners]]
  # ... other configuration ...
  [runners.docker]
    volumes = [
      "/opt/devsecops:/opt/devsecops:rw",
      "/var/run/docker.sock:/var/run/docker.sock",
      "/var/log:/var/log:rw"
    ]
    privileged = true